[workspace]
members = [
    "crates/runtime/icn-runtime",
    "crates/wallet/icn-wallet",
    "crates/agoranet/agoranet-core",
    "crates/mesh/planetary-mesh",
    "crates/common/icn-types",
    "crates/common/icn-identity-core",
    "crates/common/icn-core-types",
    "crates/tools/icn-cli",
    "tests",
]
resolver = "2"

# Optional: Configure profiles for the workspace
# [profile.release]
# lto = true
# codegen-units = 1
