[workspace]
members = [
    "crates/runtime/icn-runtime",
    "crates/wallet/icn-wallet",
    "crates/agoranet/agoranet-core",
    "crates/mesh/planetary-mesh",
    "crates/common/icn-types",
    "crates/common/icn-identity-core",
    "crates/tools/icn-cli",
    # Migrated crates
    "crates/common/icn-dag",
    "crates/runtime/icn-runtime-vm",
    "crates/runtime/icn-governance-kernel",
    "crates/wallet/icn-wallet-core",
    "crates/wallet/icn-wallet-identity",
]
resolver = "2"
