[workspace]
members = [
    "crates/runtime/icn-runtime",
    "crates/wallet/icn-wallet",
    "crates/agoranet/agoranet-core",
    "crates/mesh/planetary-mesh",
    "crates/common/icn-types",
    "crates/common/icn-identity-core",
    "crates/tools/icn-cli"
]
resolver = "2"
