[package]
name = "icn-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
# Add std::path::PathBuf if needed, but it's part of std lib 