[package]
name = "icn-identity-core"
version = "0.1.0"
edition = "2021"

[dependencies]
icn-types = { path = "../icn-types" }
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = { version = "2.0", features = ["serde", "rand_core"] }
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
serde_json = "1.0"
