name: Docs CI & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write # Allow peaceiris/actions-gh-pages to push to gh-pages branch

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material
          pip install markdown-link-check # For link checking
          # Add any other mkdocs plugins here if needed in the future
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-docs-

      - name: Run docs update script (generates READMEs, crate map, builds docs)
        run: ./scripts/update_docs.sh

      - name: Check if generated docs introduced changes (PR check)
        if: github.event_name == 'pull_request'
        run: |
          git diff --exit-code || \
            (echo "::error::Generated documentation (READMEs, crate map) is not up to date. Please run ./scripts/update_docs.sh locally and commit the changes." && exit 1)
      
      # Markdown link check - run on built site to check all generated content
      # This needs the site to be built first. The update_docs.sh script already runs mkdocs build.
      # We will check links in the 'site' directory.
      # However, markdown-link-check works on .md files, not HTML.
      # A better approach for MkDocs is to use a plugin or check links before build if possible.
      # For now, we'll focus on ensuring generation is up to date.
      # Link checking can be refined later. Let's add a placeholder for future improvement or use mkdocs linkcheck if available.

      - name: Deploy to GitHub Pages (on main branch push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: Automated docs deployment 