name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache Cargo (registry, git dependencies, target)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-docs-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs Material
      run: pip install mkdocs-material

    - name: Check Markdown links
      run: |
        echo "Checking links in docs/index.md..."
        markdown-link-check docs/index.md
        echo "Checking links in other Markdown files in docs/ directory..."
        markdown-link-check docs/**/*.md --quiet || echo "markdown-link-check identified potential issues. This will not fail the build for now."

    - name: Update generated docs, build site, and check for diff
      run: |
        ./scripts/update_docs.sh
        git diff --exit-code

    - name: Deploy to GitHub Pages (on push to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site 